### ISSUE TITLE
Exception when running self contained executable without SDK

### ISSUE THREAD

**Issue by KevinGliewe** [KevinGliewe/GCore.Source#3]
```
# ./GCore.Source.Cli --in test.txt
System.IO.DirectoryNotFoundException: Could not find a part of the path '/packs/Microsoft.NETCore.App.Ref'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserDirectories(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetDirectories(String path, String searchPattern, SearchOption searchOption)
   at GCore.Source.Scripting.ReferenceAssemblyService.GetCurrentAssemblyReferencePath(String framework, String version) in /_/src/GCore.Source.Scripting/ReferenceAssemblyService.cs:line 74
   at GCore.Source.Scripting.ReferenceAssemblyService.GetSharedFrameworkConfiguration(String framework, String version) in /_/src/GCore.Source.Scripting/ReferenceAssemblyService.cs:line 36
   at GCore.Source.Scripting.ReferenceAssemblyService..ctor(String framework_) in /_/src/GCore.Source.Scripting/ReferenceAssemblyService.cs:line 29
   at GCore.Source.Scripting.ScriptRunner..ctor(Assembly[] references, String[] imports, String[] searchPaths, String baseDirectory, IReadOnlyDictionary`2 config) in /_/src/GCore.Source.Scripting/ScriptRunner.cs:line 46
   at GCore.Source.Generators.Scripting.ScriptElement.RenderScript(CodeWriter writer) in /_/src/GCore.Source.Generators.Scripting/ScriptElement.cs:line 27
   at GCore.Source.Generators.Elements.ScriptableElement.Render(CodeWriter writer) in /_/src/GCore.Source.Generators/Elements/ScriptableElement.cs:line 49
   at GCore.Source.Generators.SourceElement.Render(CodeWriter writer) in /_/src/GCore.Source.Generators/SourceElement.cs:line 238
   at GCore.Source.Generators.Extensions.SourceElementExtensions.Render(SourceElement this) in /_/src/GCore.Source.Generators/Extensions/SourceElementExtensions.cs:line 11
   at GCore.Source.Cli.Program.Main(String[] args) in /_/src/GCore.Source.Cli/Program.cs:line 102
```

There should be a fallback for [Roslyn Scripting](https://github.com/dotnet/roslyn/blob/main/docs/wiki/Scripting-API-Samples.md) in [`ScriptRunner`](https://github.com/KevinGliewe/GCore.Source/blob/master/src/GCore.Source.Scripting/ScriptRunner.cs) if there is no SDK aviable.

**Comment by KevinGliewe** [comment]
I suspect [`RuntimeEnvironment.GetRuntimeDirectory()`](https://github.com/KevinGliewe/GCore.Source/blob/master/src/GCore.Source.Scripting/ReferenceAssemblyService.cs#L74C37-L74C37) returns an empty string it this case, but needs confirmation.

**Comment by KevinGliewe** [comment]
> I suspect [`RuntimeEnvironment.GetRuntimeDirectory()`](https://github.com/KevinGliewe/GCore.Source/blob/master/src/GCore.Source.Scripting/ReferenceAssemblyService.cs#L74C37-L74C37) returns an empty string it this case, but needs confirmation.

Looks like it resturns the directory containing the executable: https://github.com/dotnet/runtime/issues/25483#issuecomment-465088782
